
IF(_WIN_)
	FIND_PATH(OpenCV_INCLUDE_DIR NAMES opencv2 HINTS ${CMAKE_SOURCE_DIR}/../../SDK/opencv/include)
	FIND_FILE(OpenCV_DEBUG_LIB opencv_world346d.lib)
	FIND_FILE(OpenCV_RELEASE_LIB opencv_world346.lib)
ELSEIF(_OSX_)
	FIND_PATH(OpenCV_INCLUDE_DIR NAMES opencv2 HINTS "/usr/local/Cellar/opencv@3/3.4.16_10/include")
	FIND_PATH(OpenCV_LIB_DIR NAMES libopencv_calib3d.3.4.16.dylib HINTS "/usr/local/Cellar/opencv@3/3.4.16_10/lib")

	SET(OpenCV_CORE_LIB_DEBUG ${OpenCV_LIB_DIR}/libopencv_core.dylib)
	SET(OpenCV_CORE_LIB_RELEASE ${OpenCV_LIB_DIR}/libopencv_core.dylib)

	SET(OpenCV_HIGHGUI_LIB_DEBUG ${OpenCV_LIB_DIR}/libopencv_highgui.dylib)
	SET(OpenCV_HIGHGUI_LIB_RELEASE ${OpenCV_LIB_DIR}/libopencv_highgui.dylib)

	SET(OpenCV_IMGPROC_LIB_DEBUG ${OpenCV_LIB_DIR}/libopencv_imgproc.dylib)
	SET(OpenCV_IMGPROC_LIB_RELEASE ${OpenCV_LIB_DIR}/libopencv_imgproc.dylib)

	SET(OpenCV_IMGCODECS_LIB_DEBUG ${OpenCV_LIB_DIR}/libopencv_imgcodecs.dylib)
	SET(OpenCV_IMGCODECS_LIB_RELEASE ${OpenCV_LIB_DIR}/libopencv_imgcodecs.dylib)

	ADD_LIBRARY(_highgui SHARED IMPORTED)
	SET_TARGET_PROPERTIES(_highgui PROPERTIES
			IMPORTED_LOCATION_RELEASE "${OpenCV_HIGHGUI_LIB_RELEASE}"
			IMPORTED_LOCATION_DEBUG "${OpenCV_HIGHGUI_LIB_DEBUG}")

	ADD_LIBRARY(_imgproc SHARED IMPORTED)
	SET_TARGET_PROPERTIES(_imgproc PROPERTIES
			IMPORTED_LOCATION_RELEASE "${OpenCV_IMGPROC_LIB_RELEASE}"
			IMPORTED_LOCATION_DEBUG "${OpenCV_IMGPROC_LIB_DEBUG}")

	ADD_LIBRARY(_imgcodecs SHARED IMPORTED)
	SET_TARGET_PROPERTIES(_imgcodecs PROPERTIES
			IMPORTED_LOCATION_RELEASE "${OpenCV_IMGCODECS_LIB_RELEASE}"
			IMPORTED_LOCATION_DEBUG "${OpenCV_IMGCODECS_LIB_DEBUG}")
ENDIF()

IF(_WIN_)
	ADD_LIBRARY(OpenCV SHARED IMPORTED)
	SET_TARGET_PROPERTIES(OpenCV PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${OpenCV_INCLUDE_DIR};"
			IMPORTED_LINK_INTERFACE_LIBRARIES "_gflags;_gflags_nothreads"
			IMPORTED_LOCATION_RELEASE "${OpenCV_RELEASE_LIB}"
			IMPORTED_LOCATION_DEBUG "${OpenCV_DEBUG_LIB}"
	)
ELSEIF(_OSX_)
	ADD_LIBRARY(OpenCV SHARED IMPORTED)
	SET_TARGET_PROPERTIES(OpenCV PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
			INTERFACE_INCLUDE_DIRECTORIES "${OpenCV_INCLUDE_DIR};"
			IMPORTED_LINK_INTERFACE_LIBRARIES "_highgui;_imgproc;_imgcodecs"
			IMPORTED_LOCATION_RELEASE "${OpenCV_CORE_LIB_RELEASE}"
			IMPORTED_LOCATION_DEBUG "${OpenCV_CORE_LIB_DEBUG}"
	)
ENDIF()