
FIND_PATH(SuiteSparse_INCLUDE_DIR NAMES suitesparse HINTS ${CMAKE_SOURCE_DIR}/../../SDK/suitesparse/include)
FIND_PATH(SuiteSparse_LIB_DIR NAMES libamd.lib HINTS ${CMAKE_SOURCE_DIR}/../../SDK/suitesparse/lib)

SET(GHOLMOD_RELEASE_LIB ${SuiteSparse_LIB_DIR}/libcholmod.lib)
SET(GHOLMOD_DEBUG_LIB ${SuiteSparse_LIB_DIR}/libcholmodd.lib)

SET(AMD_RELEASE_LIB ${SuiteSparse_LIB_DIR}/libamd.lib)
SET(AMD_DEBUG_LIB ${SuiteSparse_LIB_DIR}/libamdd.lib)

SET(CAMD_RELEASE_LIB ${SuiteSparse_LIB_DIR}/libcamd.lib)
SET(CAMD_DEBUG_LIB ${SuiteSparse_LIB_DIR}/libcamdd.lib)

SET(CSPARSE_RELEASE_LIB ${SuiteSparse_LIB_DIR}/libcxsparse.lib)
SET(CSPARSE_DEBUG_LIB ${SuiteSparse_LIB_DIR}/libcxsparsed.lib)

SET(SUITESPARSECONFIG_RELEASE_LIB ${SuiteSparse_LIB_DIR}/suitesparseconfig.lib)
SET(SUITESPARSECONFIG_DEBUG_LIB ${SuiteSparse_LIB_DIR}/suitesparseconfigd.lib)

ADD_LIBRARY(_cholmod STATIC IMPORTED)
SET_TARGET_PROPERTIES(_cholmod PROPERTIES
	IMPORTED_LOCATION_RELEASE "${GHOLMOD_RELEASE_LIB}"
	IMPORTED_LOCATION_DEBUG "${GHOLMOD_DEBUG_LIB}"
)

ADD_LIBRARY(_amd STATIC IMPORTED)
SET_TARGET_PROPERTIES(_amd PROPERTIES
	IMPORTED_LOCATION_RELEASE "${AMD_RELEASE_LIB}"
	IMPORTED_LOCATION_DEBUG "${AMD_DEBUG_LIB}"
)

ADD_LIBRARY(_camd STATIC IMPORTED)
SET_TARGET_PROPERTIES(_camd PROPERTIES
	IMPORTED_LOCATION_RELEASE "${CAMD_RELEASE_LIB}"
	IMPORTED_LOCATION_DEBUG "${CAMD_DEBUG_LIB}"
)

ADD_LIBRARY(_cxsparse STATIC IMPORTED)
SET_TARGET_PROPERTIES(_cxsparse PROPERTIES
	IMPORTED_LOCATION_RELEASE "${CSPARSE_RELEASE_LIB}"
	IMPORTED_LOCATION_DEBUG "${CSPARSE_DEBUG_LIB}"
)

#ADD_LIBRARY(SuiteSparse STATIC IMPORTED)
#SET_TARGET_PROPERTIES(SuiteSparse PROPERTIES
#	IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
#	INTERFACE_INCLUDE_DIRECTORIES "${SuiteSparse_INCLUDE_DIR}"
#	IMPORTED_LINK_INTERFACE_LIBRARIES "_cholmod;_amd;_camd;_cxsparse"
#	IMPORTED_LOCATION_RELEASE "${SUITESPARSECONFIG_RELEASE_LIB}"
#	IMPORTED_LOCATION_DEBUG "${SUITESPARSECONFIG_DEBUG_LIB}"
#)

ADD_LIBRARY(SuiteSparse STATIC IMPORTED)
SET_TARGET_PROPERTIES(SuiteSparse PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C;CXX"
	INTERFACE_INCLUDE_DIRECTORIES "${SuiteSparse_INCLUDE_DIR}"
	IMPORTED_LOCATION_RELEASE "${CSPARSE_RELEASE_LIB}"
	IMPORTED_LOCATION_DEBUG "${CSPARSE_DEBUG_LIB}"
)


